### ISSUE TITLE
Blank screen after getting started

### ISSUE THREAD

**Issue by okcmike** [khaxis/plynx#23]
I followed the tl;dr getting started instructions.  Going to localhost:3001 redirects me to localhost:3001/graphs where I get blank screen and the attached two JS errors.

<img width="1128" alt="Screen Shot 2019-09-26 at 9 34 21 AM" src="https://user-images.githubusercontent.com/26935539/65693098-b8d56680-e041-11e9-95cb-6f1f121a459e.png">

Setup:
Chrome:  Version 77.0.3865.90 (Official Build) (64-bit)
Mac: 10.14.6
Docker desktop: 2.1.0.3

**Comment by assansanogo** [comment]
same problem here...

**Comment by khaxis** [comment]
Thank you, please run `pull` and try again.

There were two reasons:
- plynx 0.2.10 had significant changes in REST api comparing to 0.2.9 (used to be master)
- versions of docker images are not well supported.

Basically you were running different versions of frontend and backend. Now since plynx 0.2.10 is current, it should work fine.

**Comment by okcmike** [comment]
Confirmed works, thanks!
